url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Shan Khan's Portfolio
email: shankhan2020@u.northwestern.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
